services:
  # --- NODE EXPORTER (HOST METRICS) ---
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-net

  # --- Black BOX EXPORTER (Application METRICS) ---
  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    ports:
      - "9115:9115"
    networks:
      - app-net

  # --- CADVISOR (CONTAINER METRICS) ---
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-net

  # --- PROMETHEUS ---
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-net
    depends_on:
      - node-exporter
      - blackbox-exporter
      - cadvisor

  # --- GRAFANA ---
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
    - grafana-data:/var/lib/grafana
    networks:
      - app-net
    depends_on:
      - prometheus

networks:
  app-net:
    driver: bridge

volumes:
  grafana-data:
    driver: local